version: '2'
services:
  mail:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - "./searchdata:/usr/share/elasticsearch/data"
  redis:
    image: redis:3-alpine
    ports:
      - "6380:6379"
    volumes:
      - "./redis:/data"
  back:
    build: ./back
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - ELASTICSEARCH_URL=search:9200
      - MAIL_SERVER=mail
      - MAIL_PORT=1025
      - REDIS_URL=redis://redis:6379/0
    links:
      - mail
      - search
      - redis
    ports:
      - "5000:80"
    volumes:
      - "./back/src:/app"
      - "./db:/db"
      - "./log:/log"
      - "./back/requirements.txt:/requirements.txt"
    entrypoint:
      - "flask"
    command: ["run", "--host=0.0.0.0", "--port=80"]
  front:
    build: ./front
    links:
      - back
    ports:
      - "8080:8080"
    volumes:
      - "./front/src:/app/src"
      - "./front/public:/app/public"
      - "./front/packages.json:/app/packages.json"
    entrypoint:
      - "npm"
    command: ["run", "serve"]
