"""add posts table

Revision ID: 55409da10662
Revises: 75cbe2e1cbd6
Create Date: 2019-09-17 12:13:28.991266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55409da10662'
down_revision = 'f2c00d734356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'post',
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=128), nullable=True),
        sa.Column('body', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('views', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
        sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
        sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
