import uuid

articles_data = [
  {
    'articleId': uuid.uuid4(),
    "title": "Moroccan Days",
    "author": "John L",
    "category": "Travel",
    "img": "moroccandays.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Swedish Fishing",
    "author": "Rachel L",
    "category": "Leisure",
    "img": "autumnclouds.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "The Adventure Begins",
    "img": "snowcup.jpg",
    "prominent": True,
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Paris in Spring",
    "author": "John L",
    "category": "Travel",
    "img": "christmas.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Youthful Independence",
    "author": "Rachel L",
    "category": "Political",
    "img": "july4.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Trial By Fire",
    "author": "Anthony R",
    "category": "Cooking",
    "img": "firepots.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Water Ventures",
    "author": "Rachel L",
    "category": "Leisure",
    "img": "jellyfish.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Mt. Zekial",
    "author": "Rachel L",
    "category": "Travel",
    "img": "mountaincabin.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Cozumel Caves",
    "author": "Rachel L",
    "category": "Travel",
    "img": "lightcave.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Amazing Ireland",
    "author": "Rachel L",
    "category": "Travel",
    "img": "greengrass.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Cabin Fever",
    "author": "Rachel L",
    "category": "Travel",
    "img": "snowcabin.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "To the ancient ruins",
    "author": "Rachel L",
    "category": "Travel",
    "img": "ruins.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "New fashion trends",
    "author": "Rachel L",
    "category": "Travel",
    "img": "umbrella.jpg",
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Go on a vacation",
    "author": "Rachel L",
    "category": "Travel",
    "img": "adventurecave.jpg",
  },
]
