import random
import uuid
from datetime import datetime

tags = [
  {
    'tagId': tag_id + 1,
    'name': "Tag {}".format(tag_id + 1),
  }
  for tag_id in range(5)
]

articles_data = [
  {
    'articleId': uuid.uuid4(),
    "title": "Moroccan Days",
    "author": "John L",
    "category": "Travel",
    "img": "moroccandays.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Swedish Fishing",
    "author": "Rachel L",
    "category": "Leisure",
    "img": "autumnclouds.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "The Adventure Begins",
    "img": "snowcup.jpg",
    "prominent": True,
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Paris in Spring",
    "author": "John L",
    "category": "Travel",
    "img": "christmas.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Youthful Independence",
    "author": "Rachel L",
    "category": "Political",
    "img": "july4.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Trial By Fire",
    "author": "Anthony R",
    "category": "Cooking",
    "img": "firepots.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Water Ventures",
    "author": "Rachel L",
    "category": "Leisure",
    "img": "jellyfish.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Mt. Zekial",
    "author": "Rachel L",
    "category": "Travel",
    "img": "mountaincabin.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Cozumel Caves",
    "author": "Rachel L",
    "category": "Travel",
    "img": "lightcave.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Amazing Ireland",
    "author": "Rachel L",
    "category": "Travel",
    "img": "greengrass.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Cabin Fever",
    "author": "Rachel L",
    "category": "Travel",
    "img": "snowcabin.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "To the ancient ruins",
    "author": "Rachel L",
    "category": "Travel",
    "img": "ruins.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "New fashion trends",
    "author": "Rachel L",
    "category": "Travel",
    "img": "umbrella.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
  {
    'articleId': uuid.uuid4(),
    "title": "Go on a vacation",
    "author": "Rachel L",
    "category": "Travel",
    "img": "adventurecave.jpg",
    'createdAt': datetime.now(),
    'tags': [random.choice(tags) for _ in range(random.randrange(3))],
    'views': random.randrange(512),
    'comments': [],
    'commentsCount': random.randrange(128),
  },
]
